#!/usr/bin/env bash

theme=$(dirname $0)/./theme.rasi
prompt="Goodbyaa"
options="Let me think again O_O\nExit i3WM :-)"
cancel="$(echo -e "$options" | grep 'think')"
confirm="$(echo -e "$options" | grep 'Exit')"

returnn="~/.config/rofi/powermenu/powermenu"

choosen=$(echo -e "$options" | rofi -dmenu -p "$prompt" -theme $theme)

case "$choosen" in
    "$cancel") exec $returnn
    ;;
    "$confirm") i3-msg exit
    ;;
esac
