#!/usr/bin/env bash

killall -q xwallpaper &
PID1=$!

wait $PID1
xwallpaper --daemon --stretch \
    "/data/data/com.termux/files/home/.wallpaper/elaina-drinking-coffee-near-window-majo-no-tabitabi-wallpaperwaifu-com.png" &
