#!/usr/bin/env bash

theme=$(dirname $0)/./theme.rasi
options="\n󰍃\n"
prompt="Kernel: $(uptime -p)"

exitwm="~/.config/rofi/confirm/exit-i3"
shutdown="~/.config/rofi/confirm/kill-termux"

choosen=$(echo -e "$options" | rofi -dmenu -p "$prompt" -theme $theme)

case "$choosen" in
    "") xfce4-screensaver-command --lock
    ;;
    "󰍃") exec $exitwm
    ;;
    "") exec $shutdown
    ;;
esac

